/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab_1;

public class Library {
    public static void main(String[] args) {
        Library lib = new Library();
        if (lib.someLibraryMethod()) {
            System.out.println("When there is a fire, commit, push and run away");
        }
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
