/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8;

public class App {
    public String getGreeting() {
<<<<<<< HEAD
        return "Bye world.";    // Say goodbye to the world now.
=======
        return "Make world great again!";  // Trunp said so.
>>>>>>> 32febbe2ce6716a5a3074da8d6fb584e157c1218
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
