/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8;

public class App {
    public String getGreeting() {
        return "Make world great again!";  // Trunp said so.
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
